"""create payroll table

Revision ID: d143f40fab79
Revises: ad29326dd633
Create Date: 2026-06-18 22:47:24.172148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd143f40fab79'
down_revision: Union[str, Sequence[str], None] = 'ad29326dd633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payrolls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('total_working_days', sa.Integer(), nullable=True),
    sa.Column('days_present', sa.Integer(), nullable=True),
    sa.Column('leave_deductions', sa.Float(), nullable=False),
    sa.Column('overtime_bonus', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payrolls')
    # ### end Alembic commands ###
